### ISSUE TITLE
Built-in fix in Ubuntu

### ISSUE THREAD

**Issue by vidarlx** [finkrer/KeyboardChatteringFix-Linux#8]
I was using that previously, but seems like now there is a built-in feature (at least in Ubuntu >20.04) which prevents this behaviour (and works just perfect). 

Settings > Universal Access > Typing Assist  (Access X) > Bounce Keys   (turn it on)

![image](https://github.com/finkrer/KeyboardChatteringFix-Linux/assets/2722691/c7d36212-6e9d-4f21-bf93-10c86ebce26b)

**Comment by finkrer** [comment]
Hi @vidarlx. Bounce keys is an old feature of X Window System. Its main downside is listed in the README:

> it resets the delay even on filtered key presses, meaning that if you press the key fast enough, none of the presses with pass through, ever. And if the key chatters, this is bound to happen eventually and interfere with fast repeated key presses.

So it filters _your_ keypresses based on when the _fake_ keypresses occurred, which makes no sense to me. Essentially if you try to press the key very fast and it chatters, it just won't trigger at all, ever. This tool has a more advanced algorithm that specifically filters only _fake_ keypresses based on when _you_ pressed the key, and not the other way around.

Another downside is that it only works in X. As a kernel level tool, KeyboardChatteringFix-Linux works everywhere, like for example in the virtual terminal.
